# name: Batch Docker Build

# on:
#   push:
#     branches: [master]

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v2
#       - name: Docker Login
#         run: docker login filecan.xyz:5432 -u ${{ secrets.DOCKER_REGISTRY_USERNAME }} -p ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
