name: タグを公開したときにCDする


on:
  release:
    types:
    - published


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set version
        id: version
        run: |
          echo "NAME=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
          echo "BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
          echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      - name: Reffer env
        run: |
          echo $NAME
          echo $BRANCH
          echo $TAG
