name: タグを公開したときにCDする


on:
  release:
    types:
    - published


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set version
        id: version
        run: |
          echo "::set-env name=NAME::${GITHUB_REF#refs/*/}"
          echo "::set-env name=BRANCH::${GITHUB_REF#refs/heads/}"
          echo "::set-env name=TAG::${GITHUB_REF#refs/tags/}"
      - name: Reffer env
        run: |
          echo $NAME
          echo $BRANCH
          echo $TAG
